Workflows:
  ios-workflow:
    name: Weather Master iOS Build

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        distribution_type: development
        bundle_identifier: O.TEU.BUNDLE.ID

    scripts:
      - name: Add ios platform
        script: |
          flutter create . --platforms=ios

      - name: Verify project structure
        script: |
          ls -la

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
